--- 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "https://partridge-eureka-server.cfapps.io/eureka/"
server: 
  port: 9600
spring: 
  application: 
    name: partridge-weather-api
  cache: 
    cache-names: "places, placesList"
    caffeine: 
      spec: 
        expireAfterAccess: 10s
        maximumSize: 100
weather: 
  APPID: 4d1dea7b144f09ca558a4702672d2eee
  BASEURL: "https://api.openweathermap.org/data/"
  UNITS: metric
  VERSION: 2.5/