--- 
server: 
  port: 9100
spring: 
  application: 
    name: partridge-register-user
    data: "mongodb:port=27118"
eureka:
  client:
    serviceUrl:
      defaultZone: https://partridge-eureka-server.cfapps.io/eureka/
