--- 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "https://partridge-eureka-server.cfapps.io/eureka/"
server: 
  port: 9800
spring: 
  application: 
    name: partridge-image-api
multipart:
  max-file-size: 100MB
  max-request-size: 100MB
